#!/bin/bash
# mise description="Build the project using Swift Package Manager"
set -euo pipefail

swift build --product AppleBundleSizeAnalyzer --package-path $MISE_PROJECT_ROOT --configuration release