#!/bin/bash
# mise description="Performs additional tasks that are necessary to work in this repository"

set -euo pipefail

pnpm install -C $MISE_PROJECT_ROOT/docs/
if [[ "$(uname)" == "Darwin" ]]; then
    tuist install --path $MISE_PROJECT_ROOT
fi